[package]
name = "ch8_resolve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
clap = "2.34.0"
trust-dns = {version= "0.16", default-deatures=false}